version: '2.1'

networks:
  default:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "account"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: 
        --character-set-server=utf8mb4 
        --collation-server=utf8mb4_unicode_ci
    networks:
      default:
        aliases: 
          - mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 3307:80
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_USER: "root"
        PMA_PASSWORD: "root"
        PMA_ARBITRARY: 1
      networks:
        default:
          aliases: 
            - phpmyadmin